metrics:
  crypto:
    url: 
      - "https://www.livecoinwatch.com/price/Avalanche-AVAX"
      - "https://www.livecoinwatch.com/price/Ethereum-ETH"
      - "https://www.livecoinwatch.com/price/Bitcoin-BTC"
    type: gauge
    description: "Exports the current coin value based on the web scrape"
